import './globals.css'
import { Inter } from 'next/font/google'
import Foot from '@/components/footer/Foot'
import Navbar from '@/components/navbar/Navbar'
import AuthProvider from '@/components/AuthProvider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
      <header>
         <Navbar/>
      </header>
      <main>
        {children}
        </main>
         <footer><Foot/></footer> 
         </AuthProvider>
      </body>
    </html>
  )
}
